version: '3.8'
services:
    frontend:
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /app
        volumes:
            - ./:/app
        ports:
            - '${FRONTEND_PORT}:8888'